### ISSUE TITLE
Standarize error handling

### ISSUE THREAD

**Issue by guzman-raphael** [walkerlab/orcapod#25]
e.g. based on an `OrcaError` enum

These seem like interesting options:
- https://stackoverflow.com/questions/48430836/rust-proper-error-handling-auto-convert-from-one-error-type-to-another-with-que
- https://doc.rust-lang.org/rust-by-example/error/multiple_error_types/wrap_error.html

**Comment by eywalker** [comment]
Per discussion, we will aim to implement `orcapod` specific error struct `Error` with specific underlying `Enum` to signify distinct error types. `Error` will implement `From` trait handle conversion from well-known error types. Furthermore, we will implement `From<orcapod::Error>` on standard errors including `std::error::Error`. A reference implementation approach is serde-yaml (https://docs.rs/serde_yaml/latest/src/serde_yaml/error.rs.html#12).
